// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import BiographyController from "./biography_controller"
application.register("biography", BiographyController)

import PostModalController from "./post_modal_controller"
application.register("post-modal", PostModalController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
